### PR TITLE
Quick hack to get GfxTablet working with Gimp 2.8 on kernel 4.17

### PR DESCRIPTION
**Pull request by tonyg**
This switches from the old `uinput_user_dev` method to the new `ioctl`-based `UI_ABS_SETUP`/`UI_DEV_SETUP` method that X's libinput seems to need these days. After these changes, the device worked in X windows and thus gimp and inkscape; without these changes, `Xorg.0.log` complained about missing resolution information.

### CODE REVIEW

**Comment by 54D-R0807** [comment]
Works for me too, running: openSUSE Leap 15.0; 4.12.14-lp150.12.16-default #1 SMP Tue Aug 14 17:51:27 UTC 2018 (28574e6) x86_64 x86_64 x86_64 GNU/Linux

**Comment by atondwal** [comment]
Works for me on Ubuntu LTS 18; Thanks!

**Comment by Nikomaru** [comment]
With system update, and uninstall and reinstall, works in GIMP and on the whole desktop for current Arch. Thank you for that!

**Comment by Zanark** [comment]
I got the following errors after compiling the committed changes

```
networktablet.c: In function ‘init_device’:
networktablet.c:54:35: error: storage size of ‘abs_setup’ isn’t known
           struct uinput_abs_setup abs_setup;
                                   ^
networktablet.c:55:31: error: storage size of ‘setup’ isn’t known
           struct uinput_setup setup;
                               ^
networktablet.c:65:25: error: ‘UI_ABS_SETUP’ undeclared (first use in this function)
           if (ioctl(fd, UI_ABS_SETUP, &abs_setup) < 0)
                         ^
networktablet.c:65:25: note: each undeclared identifier is reported only once for each function it appears in
networktablet.c:97:25: error: ‘UI_DEV_SETUP’ undeclared (first use in this function)
           if (ioctl(fd, UI_DEV_SETUP, &setup) < 0)
                         ^
<builtin>: recipe for target 'networktablet' failed
make: *** [networktablet] Error 1

```

**Comment by Zanark** [comment]
I am using Linux Mint 4.10.0-38-generic

**Comment by tonyg** [comment]
@Zanark ok, so this is weird. Mint 18.3's linux 4.10.0-38 headers include a uinput.h that doesn't have the version 0.5 patches from August 2015! The mainline 4.10 kernel *does* have the 0.5 patches.

Check your /usr/include/linux/uinput.h file - if it *doesn't* have the following, you will have to upgrade Mint somehow to have a linux kernel and headers package that *does*:

```
 * Changes/Revisions:
 *	0.5	08/13/2015 (David Herrmann <dh.herrmann@gmail.com> &
 *			    Benjamin Tissoires <benjamin.tissoires@redhat.com>)
 *		- add UI_DEV_SETUP ioctl
 *		- add UI_ABS_SETUP ioctl
 *		- add UI_GET_VERSION ioctl
```

(I see you're now on 4.15.0-34 -- and if you're suffering the same problem there, the cause is likely the same.)

**Comment by tonyg** [comment]
@Zanark, Linux Mint 19 "Tara" ships with 4.15.0-20-generic headers that include the 0.5 uinput.h changes, and I have just compiled `networktablet` using a live install ISO of that system.

**Comment by Zanark** [comment]
@tonyg This works like a charm now. I've installed Tara 4.15.0-38-generic and it works perfectly. **However** when I start the application, my touchpad gets disabled and I'm unable to activate it even after closing the application. Can you please help me out with this.

**Comment by tonyg** [comment]
Hi @Zanark - I'm glad you got it working to the extent you did, but I'm afraid I have no idea how to help you debug your touchpad issue. Sorry.

**Comment by Zanark** [comment]
Okay, I'll try to find a solution and post it here for someone who might face this issue in the future.
Thanx a ton for your help :smile:

**Comment by wech71** [comment]
Sorry,

same here as rfc2822. I just don't have any time to spare on the project anymore. Also I have near no knowlege about linux/unix development.

**Comment by Vrak** [comment]
Working with Kubuntu 18.04

**Comment by loopyd** [comment]
This is a useful program to artists sad to see it falling to maintenance
issues.  I have been hard at work in learning gcc compiler over the last 3
months unfortunately my skill is not up to par with maintaining the project
as a head but I might know enough to test if it is asked of me.  I have
some experience in *nix but not enough to call myself an expert sadly.

**Comment by tonyg** [comment]
> i have wrote a mail to rfc2822 on his domain at bitfire.at
> and he told, he have absolute no time and he would over give
> the GfxTablet to an person who want it maintain and further developing
> and where want overtake this project.

I can't take on full maintainership, but I am definitely able to do things like e.g. merge in this pull request to mainline. @rfc2822, if you'd like to grant me the commit bit I'd be happy to do such small housekeeping tasks as and when I have time.

**Comment by tonyg** [comment]
OK - these changes are on master now.
